export default function About() {
  return (
    <div style={{
      minHeight: '100vh', background: '#08080f',
      color: '#e2e8f0', fontFamily: "'JetBrains Mono','SF Mono',monospace",
      padding: '40px 20px',
    }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>

        {/* Header */}
        <div style={{ marginBottom: 48 }}>
          <div style={{ fontSize: 11, color: '#7C3AED', letterSpacing: '0.15em', marginBottom: 12 }}>
            ABOUT OTJ
          </div>
          <h1 style={{ fontSize: 32, fontWeight: 800, color: '#f1f5f9', margin: 0, lineHeight: 1.2 }}>
            Built by an analyst.<br />
            <span style={{ color: '#7C3AED' }}>Not a tout.</span>
          </h1>
        </div>

        {/* Origin story */}
        <section style={{ marginBottom: 48 }}>
          <p style={{ fontSize: 14, color: '#94a3b8', lineHeight: 1.8, margin: '0 0 16px' }}>
            Overtime Journal started with a simple observation: the same quantitative methods
            used to model risk in financial institutions can be applied to sports betting markets —
            and most public-facing tools don't come anywhere close to that level of rigor.
          </p>
          <p style={{ fontSize: 14, color: '#94a3b8', lineHeight: 1.8, margin: 0 }}>
            The founder spent years building predictive models in finance — probability of default
            calculators, ensemble scoring systems, delinquency pipelines, and performance dashboards
            for institutional lending portfolios. When you spend your days thinking in risk-adjusted
            probabilities, you start seeing betting lines differently.
          </p>
        </section>

        {/* Divider */}
        <div style={{ borderTop: '1px solid rgba(255,255,255,0.06)', marginBottom: 48 }} />

        {/* The model */}
        <section style={{ marginBottom: 48 }}>
          <div style={{ fontSize: 11, color: '#7C3AED', letterSpacing: '0.15em', marginBottom: 16 }}>
            THE APPROACH
          </div>
          <h2 style={{ fontSize: 20, fontWeight: 700, color: '#f1f5f9', margin: '0 0 20px' }}>
            Quant finance logic. Sports data inputs.
          </h2>

          <div style={{ display: 'grid', gap: 16 }}>
            {[
              {
                icon: '📊',
                title: 'Ensemble Modeling',
                body: 'OTJ\'s edge scores are generated by a multi-factor ensemble model — not a single stat or gut feel. Multiple signals are weighted, cross-validated, and combined into a single confidence score between 0–100.',
              },
              {
                icon: '⚡',
                title: 'Fresh Data, Every Day',
                body: 'The pipeline pulls live odds, injury reports, rest data, pace metrics, and defensive ratings daily. Stale data is the enemy of good models — everything recalculates before tip-off.',
              },
              {
                icon: '🔒',
                title: 'Opening Line Discipline',
                body: 'Edge is always calculated from the opening line, not the current line. This is standard practice in serious quantitative analysis — line movement is signal, not noise to be chased.',
              },
              {
                icon: '📉',
                title: 'Injury Pricing Intelligence',
                body: 'Not all injuries are equal. OTJ classifies each scratch as long-term (already priced in), mid-term (likely priced in), or fresh (may not be priced in yet) — and adjusts edge scores accordingly.',
              },
            ].map(({ icon, title, body }) => (
              <div key={title} style={{
                background: 'rgba(124,58,237,0.06)',
                border: '1px solid rgba(124,58,237,0.15)',
                borderRadius: 12, padding: '20px 24px',
                display: 'flex', gap: 16,
              }}>
                <div style={{ fontSize: 24, flexShrink: 0 }}>{icon}</div>
                <div>
                  <div style={{ fontSize: 13, fontWeight: 700, color: '#f1f5f9', marginBottom: 6 }}>{title}</div>
                  <div style={{ fontSize: 12, color: '#6b7280', lineHeight: 1.7 }}>{body}</div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Divider */}
        <div style={{ borderTop: '1px solid rgba(255,255,255,0.06)', marginBottom: 48 }} />

        {/* What we are not */}
        <section style={{ marginBottom: 48 }}>
          <div style={{ fontSize: 11, color: '#7C3AED', letterSpacing: '0.15em', marginBottom: 16 }}>
            WHAT WE'RE NOT
          </div>
          <div style={{ display: 'grid', gap: 10 }}>
            {[
              'We don\'t sell picks. The analysis is free.',
              'We don\'t post fake records. Every pick is logged before tip-off and graded publicly.',
              'We don\'t chase steam. Lines are locked at open.',
              'We don\'t do hype. If the model doesn\'t see edge, we say so.',
            ].map((line, i) => (
              <div key={i} style={{
                display: 'flex', gap: 12, alignItems: 'flex-start',
                fontSize: 13, color: '#94a3b8', lineHeight: 1.6,
              }}>
                <span style={{ color: '#7C3AED', flexShrink: 0, marginTop: 1 }}>✓</span>
                {line}
              </div>
            ))}
          </div>
        </section>

        {/* Divider */}
        <div style={{ borderTop: '1px solid rgba(255,255,255,0.06)', marginBottom: 48 }} />

        {/* Record */}
        <section style={{ marginBottom: 48 }}>
          <div style={{ fontSize: 11, color: '#7C3AED', letterSpacing: '0.15em', marginBottom: 16 }}>
            TRACK RECORD
          </div>
          <p style={{ fontSize: 14, color: '#94a3b8', lineHeight: 1.8, margin: 0 }}>
            Every pick is timestamped and publicly logged before the game starts.
            No retroactive picks. No cherry-picking. The record page shows everything — wins, losses, and pushes.
            That's the only accountability that matters.
          </p>
        </section>

        {/* Disclaimer */}
        <div style={{
          background: 'rgba(255,255,255,0.02)',
          border: '1px solid rgba(255,255,255,0.06)',
          borderRadius: 10, padding: '16px 20px',
          fontSize: 11, color: '#374151', lineHeight: 1.6,
        }}>
          ⚠️ OTJ is for informational and entertainment purposes only. Nothing on this site constitutes financial or betting advice. Always gamble responsibly. 1-800-GAMBLER.
        </div>

      </div>
    </div>
  );
}
